version: '3'
services:
  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-jcr:${ARTIFACTORY_VERSION}
    container_name: artifactory
    depends_on:
      - postgres
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    # ports:
      # - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT} # # # #
      # - 8081:8081 # for artifactory communication# for artifactory communication# for artifactory communication# for artifactory communication
    volumes:
      - ${ROOT_DATA_DIR}/var:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  nginx:
    image: ${DOCKER_REGISTRY}/jfrog/nginx-artifactory:${ARTIFACTORY_VERSION}
    container_name: nginx
    depends_on:
      - artifactory
    # network_mode: service:artifactory
    ports:
      - 9080:9080
      - 9443:9443
    volumes:
      - ${ROOT_DATA_DIR}/var/data/nginx:/var/opt/jfrog/nginx
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ART_BASE_URL=http://artifactory:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - NGINX_LOG_ROTATE_COUNT=${NGINX_LOG_ROTATE_COUNT}
      - NGINX_LOG_ROTATE_SIZE=${NGINX_LOG_ROTATE_SIZE}
      - SSL=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:13.2-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=password
    # ports:
    #   - 5432:5432
    volumes:
      - ${ROOT_DATA_DIR}/var/data/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
