global:
  name: consul
  datacenter: local1

server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
ui:
  enabled: true
  service:
    type: 'NodePort'

connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: false

# enable Custom Repository Definitions (CRD)
controller:
  enabled: true
